### ISSUE TITLE
Delete composer binary from vendor after installing all packages

### ISSUE THREAD

**Issue by omarlopesino** [Metadrop/drupal-dev#12]
Using composer from vendor is not recommended, as composer must not be coupled to the internal project libraries. Using it may lead to side effects as there may be problems in autoloading.

## Proposed resolution

- **Discarded** Adding a command at post-install-cmd to delte the binary. It didn't work.
- Composer plugin that removes it. It can be part of drupal dev or a separate package.

**Comment by jonhattan** [comment]
This plugin looks promising https://github.com/liborm85/composer-vendor-cleaner

**Comment by omarlopesino** [comment]
Thanks, i didn't know about it. 
I have tested it and it works fine.

I will add this dependency to the drupal-dev stack. Then, projects must configure their own extras setting up to delete vendor's composer..

It is only needed to add:

```
  "dev-files": {
    "bin": [
      "composer"
    ]
  }
```

For our projects, we can add this at default aljibe composer.json configuration, so that it is always present in new projects. In legacy project, it can be added manually after upgrading metadrop/drupal-dev

**Comment by omarlopesino** [comment]
Released at [v2.6.0](https://github.com/Metadrop/drupal-dev/releases/tag/v2.6.0)
